# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlatedRestaurant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'SwiftLint'
# Pods for PlatedRestaurant

  target 'PlatedRestaurantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlatedRestaurantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
